name: Update GitHub Stats in README

on:
  schedule:
    - cron: "0 */1 * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    name: Refresh GitHub Stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Latest GitHub Stats
        run: curl -s "https://github-readme-stats.vercel.app/api?username=cronenberg64&hide_title=false&hide_rank=true&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&theme=monokai&locale=en&hide_border=false" -o stats.png

      - name: Fetch Latest GitHub Activity Graph
        run: curl -s "https://github-readme-activity-graph.vercel.app/graph?username=cronenberg64&theme=monokai&radius=0&area=true" -o activity.png

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "🔄 Auto-updated GitHub stats & activity graph" || exit 0
          git push
